### ISSUE TITLE
@expo/metro-config not working in new project

### ISSUE THREAD

**Issue by sisoalbert** [ReactNativeSchool/react-native-fundamentals#1]
Error: Cannot find module '@expo/metro-config'
Require stack:
- C:\Users\user-pc\Desktop\coding\native\react-native-fundamentals\metro.config.js
- C:\Users\user-pc\Desktop\coding\native\react-native-fundamentals\node_modules\cosmiconfig\node_modules\import-fresh\index.js
- C:\Users\user-pc\Desktop\coding\native\react-native-fundamentals\node_modules\cosmiconfig\dist\loaders.js
- C:\Users\user-pc\Desktop\coding\native\react-native-fundamentals\node_modules\cosmiconfig\dist\createExplorer.js
- C:\Users\user-pc\Desktop\coding\native\react-native-fundamentals\node_modules\cosmiconfig\dist\index.js
- C:\Users\user-pc\Desktop\coding\native\react-native-fundamentals\node_modules\react-native\node_modules\@react-native-community\cli\build\tools\config\readConfigFromDisk.js
- C:\Users\user-pc\Desktop\coding\native\react-native-fundamentals\node_modules\react-native\node_modules\@react-native-community\cli\build\tools\config\index.js
- C:\Users\user-pc\Desktop\coding\native\react-native-fundamentals\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\install\install.js
- C:\Users\user-pc\Desktop\coding\native\react-native-fundamentals\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\index.js
- C:\Users\user-pc\Desktop\coding\native\react-native-fundamentals\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js
- C:\Users\user-pc\Desktop\coding\native\react-native-fundamentals\node_modules\react-native\local-cli\cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\user-pc\Desktop\coding\native\react-native-fundamentals\metro.config.js:1:30)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)

**Comment by majayjayy** [comment]
I'm getting the same error and haven't found a fix yet. Is there a solution to this?

**Comment by spencercarli** [comment]
Sorry for the delay on this! For some reason I had notifications turned off on this repo.

This issue has been resolved by 0914332dc86c51d97424000af4fe4fff4b8fd3b2.

**Comment by aqabawe** [comment]
Hello @spencercarli, I'm getting the same issue with the latest code.

```
expo diagnostics

  Expo CLI 4.0.17 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 15.6.0 - /usr/local/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.4.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 28, 29, 30
        Build Tools: 28.0.3, 30.0.3
        System Images: android-29 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6953283
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.0 => 40.0.0
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed
```

**Comment by spencercarli** [comment]
Thanks for letting me know @aqabawe. I'm thinking the issue may be Node v15 (Expo doesn't officially support that version of node).

That said, I just installed @expo/metro-config and tested the project using the same Node & NPM version as you and it worked.

Go ahead and pull the project down again, reinstall the packages, and let me know if it works for you.
